name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
          boost_version: 1.81.0
          boost_install_dir: /home/runner/work/sigmatcher/sigmatcher/boost/boost-1.81.0-ubuntu-18.04-gcc-static+shared-x86
    - name: make
      run: make
    - name: make test
      run: make test
