name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Boost
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev
    - name: make
      run: make
    - name: make test
      run: make test
